version: '2'
services:
  backend:
    image: 7robertodantas/backend:current
    container_name: backend
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/meformei
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - backend-static:/usr/src/app/public
      - backend-uploads:/usr/src/app/uploads
    links:
      - mysql
    depends_on:
      - mysql
    command: bash -c "deploy/wait-for-it.sh mysql:3306 -t 0 && npm start"

  mysql:
    image: "mysql:8.0"
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=meformei
    ports:
      - "3306:3306"

  nginx:
    image: "nginx:1.13"
    container_name: nginx
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../.:/srv/meformei:ro
      - backend-static:/srv/meformei/backend:ro
      - backend-uploads:/srv/meformei/uploads:ro
    links:
      - backend

volumes:
  backend-static:
  backend-uploads:
